## Append samples you want in your CSV to this file as resources ##
resources:
- appstudio_v1alpha1_application.yaml
- appstudio_v1alpha1_component.yaml
- appstudio_v1alpha1_componentdetectionquery.yaml
- appstudio_v1alpha1_applicationsnapshotenvironmentbinding.yaml
- appstudio_v1alpha1_applicationsnapshot.yaml
- appstudio_v1alpha1_applicationpromotionrun.yaml
- appstudio_v1alpha1_environment.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
