# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/appstudio.redhat.com_applications.yaml
- bases/appstudio.redhat.com_components.yaml
- bases/appstudio.redhat.com_componentdetectionqueries.yaml
- bases/appstudio.redhat.com_applicationsnapshotenvironmentbindings.yaml
- bases/appstudio.redhat.com_applicationsnapshots.yaml
- bases/appstudio.redhat.com_promotionruns.yaml
- bases/appstudio.redhat.com_environments.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
